### ISSUE TITLE
Analyse security threats and resolve High impact CVEs

### ISSUE THREAD

**Issue by jonfreedman** [symphonyoss/hubot-symphony#1]
When running Coverity on the hubot-symphony codebase it finds 0 lines of code to analyse. It may be possible to analyse compiled JavaScript.

**Comment by maoo** [comment]
It may be worth to investigate https://codeclimate.com/ , as discussed; it can provide the same security validation features provided by Coverity.

**Comment by jonfreedman** [comment]
Code Climate is now running on any changes but it's just applying coffeelint not searching for any vulnerabilities.  VersionEye claims no known vulnerabilities in dependencies, not sure what it used to decide that.  I will investigate further.

**Comment by maoo** [comment]
What about https://www.npmjs.com/package/auditjs ?

**Comment by jonfreedman** [comment]
That took me to https://nodesecurity.io/

We must be getting close to the record for the most static analysis run on the smallest amount of code

**Comment by jonfreedman** [comment]
Now being validated by nodescurity @ https://nodesecurity.io/orgs/symphonyoss/projects/9309ce59-9a6b-43a9-b7bb-54c6f0117e0a
