### ISSUE TITLE
Behind a proxy and bypass proxy for internal url

### ISSUE THREAD

**Issue by ChristopheLA** [symphonyoss/hubot-symphony#18]
Hello
i'm behind a corporate proxy 
I export HTTP_PROXY and HTTPS_PROXY environment value in the script which start the Symphony Hubot.
We have a Local KeyManager, and  we setup the environment variable HUBOT_SYMPHONY_KM_HOST to the correct value. When Symphony redirec to the KM url , the Hubot  reach the Proxy as well...and should not for internal url.
So we need to bypass proxy settings for internal url. How can we do that ? 

Thanks for your help

**Comment by jonfreedman** [comment]
Try NO_PROXY as described here https://github.com/request/request/blob/master/README.md#proxies
