### ISSUE TITLE
Run diagnostic command continuously against ODP

### ISSUE THREAD

**Issue by maoo** [symphonyoss/hubot-symphony#29]
It would be very cool to instruct Travis CI to run the diagnostic command (on every commit) against the Foundation Dev Pod (foundation-dev.symphony.com).
In order to achieve it, it is necessary to:
1. download the User Identity certificates in the build box; this is now possible and the symphony-java-sample-bots project already runs integration-tests successfully - https://travis-ci.org/symphonyoss/symphony-java-sample-bots
2. run the diagnostic command with npm (just follow https://github.com/symphonyoss/hubot-symphony/blob/dev/run-odp.sh)
3. send a message - from another service account - to the one that executed the diagnostic command on step 2

The only part that is missing is 3 and I'm not sure if hubot-symphony has the code to allow it.

**Comment by maoo** [comment]
Got it working on branch https://github.com/symphonyoss/hubot-symphony/tree/integration-testing ; the following environment variables are now provided in the Travis build environment:
```
BOT_USER_CERT=[secure]
BOT_USER_KEY=[secure]
SENDER_USER_CERT=[secure]
SENDER_USER_KEY=[secure]
SENDER_USER_PASSWORD=[secure]
BOT_USER_PASSWORD=[secure]
BOT_USER_EMAIL=[secure]
SENDER_USER_EMAIL=[secure]
```

The script https://github.com/symphonyoss/hubot-symphony/blob/integration-testing/run-odp.sh uses them to run the diagnostic; in a separate thread, a message should be sent, from the sender to the bot user.

Please note that run-odp.sh redirects output to /dev/null, to avoid sensitive data to be printed out; without the redirect, the following string would be printed out:
```
hubot-symphony@ diagnostic /home/travis/build/symphonyoss/hubot-symphony
> coffee src/diagnostic.coffee "--publicKey" "...." "--privateKey" "..." "--passphrase" "..." "--host" "foundation-dev.symphony.com" "--agenthost" "foundation-dev-api.symphony.com" "--kmhost" "foundation-dev-api.symphony.com" "--sessionhost" "foundation-dev-api.symphony.com"
```

There may be a better way to do it, in order to preserve debug statements from the node logic, but avoid printing out the initial command.

Successful Travis run - https://travis-ci.org/symphonyoss/hubot-symphony/builds/187795809 (I needed to manually send a message to the mozart user, in order to complete the build)

**Comment by jonfreedman** [comment]
In order to prevent secrets being written to the travis logs I created a new integration test rather than calling the diagnostic.  It can be extended as necessary to test more functionality.  I am not sure what will happen if two foundation projects or even two branches/commits of the same project attempt to run integration tests at the same time using the same certificates though.
The bot account we're using is also actually in use on the AWS instance I am running...
Lets discuss further in the new year.

**Comment by maoo** [comment]
Thanks @jonfreedman ; I suppose - looking at the commits - that the test is called `pingpong` and reads environment variables to resolve endpoints, certificate paths and passwords.

I'll run it locally first and later integrate it with Travis CI; as a confirmation, can I run this IT test simply typing `npm run pingpong` from the project root?

**Comment by jonfreedman** [comment]
Hi Mao, it's already running on each commit. To run manually you need to set all the environment variables and then `npm run-script it`
Could you do me a favour and email me the p12 cert for the second account so I can run locally too? 

Cheers 

Jon 

---- On Mon, 02 Jan 2017 12:19:55 +0000 notifications@github.com wrote ----

Thanks @jonfreedman ; I suppose - looking at the commits - that the test is called pingpong and reads environment variables to resolve endpoints, certificate paths and passwords.

I'll run it locally first and later integrate it with Travis CI; as a confirmation, can I run this IT test simply typing npm run pingpong from the project root?

**Comment by maoo** [comment]
That's awesome, I see that Travis is running green builds, great stuff!

I've sent you the certificates via Symphony chat; marking this issue as closed, feel free to reopen if there's anything else to address.
