### ISSUE TITLE
Test git-release for hubot-symphony first release and document Version management

### ISSUE THREAD

**Issue by maoo** [symphonyoss/hubot-symphony#3]
- Run a test (dry) execution of git-release - https://www.npmjs.com/package/git-release
- Document (in README.md) what changes when a main/major/minor version change is released (keep it simple for now, considering code has not an extensive architecture)
- Document in details the release process in https://symphonyoss.atlassian.net/wiki/display/FM/Software+Development+Onboarding#SoftwareDevelopmentOnboarding-NodeJsrelease(WIP) and link it from the project's `README.md`

**Comment by maoo** [comment]
It appears that git-release doesn't handle the publishing part. Instead https://github.com/phuu/npm-release does it all; to bring this to the next level, https://github.com/semantic-release/semantic-release automates releases via commit messages

@jonfreedman , which one you'd prefer to start with?

**Comment by jonfreedman** [comment]
Lets use semantic-release it sounds great

**Comment by jonfreedman** [comment]
I've added commitizen (if you want to write commits from the command line) and a pre-commit hook to validate the commit message format.  Hopefully the badges on the readme are sufficient in terms of documentation.
Version 1.0.0 is now on npm, we can remove it if necessary @ https://www.npmjs.com/package/hubot-symphony

**Comment by maoo** [comment]
Great stuff, I'll keep this issue open so I can complete the documentation (I'll look at the commit message and link to commitizen). Thank you @jonfreedman !

**Comment by maoo** [comment]
Doc available on https://symphonyoss.atlassian.net/wiki/display/FM/Project+Infrastructure
