### ISSUE TITLE
Category X license used in bcrypt-pbkdf package

### ISSUE THREAD

**Issue by maoo** [symphonyoss/hubot-symphony#35]
The following package is fetched a transitive dependency of hubot-symphony (via `request@2.79.0, http-signature@1.1.1, sshpk@1.10.2`)

https://www.npmjs.com/package/bcrypt-pbkdf

It uses a BSD Clause 4 license - https://spdx.org/licenses/BSD-4-Clause , which is catalogued by Apache as "MAY NOT BE INCLUDED WITHIN APACHE PRODUCTS" - http://apache.org/legal/resolved.html#category-x

**Comment by maoo** [comment]
Here's the smoking gun - https://github.com/symphonyoss/hubot-symphony/blob/master/package.json#L37

**Comment by maoo** [comment]
@jonfreedman - do you confirm that `request` is essential for the core functionality of hubot-symphony?

**Comment by jonfreedman** [comment]
I'm sure I could re-write this to not use it, but it's the 28th most populate package on npm and used in 18,150 dependent projects...

**Comment by copiesofcopies** [comment]
Hi @jonfreedman, thanks for your response. I know it's a pain to reengineer something that's working for legal reasons. But unfortunately, despite this package's popularity, the 4-clause BSD license that it uses raises significant potential problems for our downstream users. The problem is clause 3, often referred to as the "obnoxious advertising clause," which says:
> All advertising materials mentioning features or use of this software must display the following acknowledgement: This product includes software developed by Niels Provos.
As minor as this requirement looks on paper, compliance can be quite burdensome, potentially requiring legal review of marketing materials. For this reason, the license is not only on the Apache Software Foundation's blacklist, but may also be prohibited by the open source policies of our prospective users.

More practically, since the license is considered incompatible with the GPL, it significantly restricts downstream combinations with a wide range of open source components.

**Comment by maoo** [comment]
PR for automated checking is in place - https://github.com/symphonyoss/hubot-symphony/pull/34

The Travis build currently fails on bcrypt-pbkdf package.

**Comment by maoo** [comment]
Found an interesting info, while browsing npm deps; sshpk package uses the incriminated package (bcrypt-pbkdf) as of version 1.10.0, however the library used in hubot-symphony needs 1.7.0 or above; this means that we can force sshpk version to be e1.9.0 and avoid any issue.

https://www.versioneye.com/nodejs/sshpk/1.10.0
https://www.versioneye.com/nodejs/sshpk/1.9.2

I'll try to make the change and rerun the scanning.

**Comment by copiesofcopies** [comment]
I emailed the author (@provos) of the BSD-4-Clause licensed portions of this library (blowfish.c) to ask if he would be willing to license it under a 3-clause BSD license. Maybe a long shot, but worth a try -- would make the licensing of the OpenBSD Blowfish implementation consistent with the license for OpenBSD as a whole.

**Comment by maoo** [comment]
I managed to fix the build issue by instructing bithound to only warn (and not fail) on outdated dependencies.

To recap, we've pinned the sshpk version to a version (1.9.2) that doesn't bring the incriminated package/license; this is just a temporary measure, until we figure out how to solve this issue permanently.

@jonfreedman - could you please review #34 , now that all checks are passing?

Thanks!

**Comment by provos** [comment]
@copiesofcopies you have my permission to remove the advertising clause.

**Comment by copiesofcopies** [comment]
@provos Thank you! Very kind of you to resolve this for us. And thanks to @provos '97 for the code ;)

**Comment by copiesofcopies** [comment]
I submitted a pull request upstream to remove the advertising clause: https://github.com/joyent/node-bcrypt-pbkdf/pull/3

**Comment by arekinath** [comment]
Upstream PR merged. And `sshpk`'s dep is on `^1.0.0`, so things should just magically work if you un-pin it now.

FWIW, the `bcrypt-pbkdf` use in `sshpk` is entirely optional (only used for very new kinds of password-protected SSH keys, and only `require()`'d if you actually try to use parse one). But it seems `npm` doesn't give us any way to do `optionalDependencies` that actually behave as if they're optional, sadly.

**Comment by maoo** [comment]
Thanks @arekinath ! This issue can be closed now.
