### ISSUE TITLE
Check hubot project status with GitHub

### ISSUE THREAD

**Issue by jonfreedman** [symphonyoss/hubot-symphony#46]
https://github.com/github/hubot/blob/master/CONTRIBUTING.md says

> We like to at least comment on, if not accept, pull requests within a few days.

but the last commit to hubot was May 2016 and the pull request to add Symphony to the list of adapters has sat in their queue for 8 months (https://github.com/github/hubot/pull/1228).

Would be great to get some colour from GitHub directly on what's going on with the project (if it's long-term maintenance no big deal, just clear the PR queue...)

**Comment by maoo** [comment]
I guess we can close this @jonfreedman ?
