### ISSUE TITLE
Define Foundation Quality Acceptance criteria for NodeJS

### ISSUE THREAD

**Issue by maoo** [symphonyoss/hubot-symphony#5]
Add specific items in  https://symphonyoss.atlassian.net/wiki/display/FM/Quality+Acceptance+Criteria that apply to NodeJS/NPM ecosystem (especially for NPMJS artifact publication, see QUAL-4 as example)

Wait for issue #3 to understand how a package.json must be defined in order to run a release.

**Comment by maoo** [comment]
First update to https://symphonyoss.atlassian.net/wiki/display/FM/Software+Development+Onboarding

**Comment by jonfreedman** [comment]
The tools I've found so far in addition to travis/coveralls:

- https://codeclimate.com/ : runs coffeelint and can parse code coverage
- https://nodesecurity.io/ : checks for vulnerabilities
- https://www.bithound.io/ : runs coffeelint, some additional analysis and checks for vulnerabilities
- https://www.versioneye.com/ : checks package.json for 1st level dependencies against latest version, license & known vulnerabilities

I've requested github auth for bithound against symphonyoss, it looks like that may most of these

**Comment by maoo** [comment]
This is great, thanks for that!

I've updated https://symphonyoss.atlassian.net/wiki/display/FM/Software+Development+Onboarding with all the listed systems

I've granted access to bithound too, it spotted an issue that I tracked on #6

We still need to figure out the NPM "scope" definition, which relates with ssf npm organisation, although it's better to discuss that on #2
