### ISSUE TITLE
Correct copyright notices in NOTICE and source headers

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/hubot-symphony#7]
The [legal acceptance criteria](https://symphonyoss.atlassian.net/wiki/display/FM/Legal+Acceptance+Criteria) had previously stated that all contributed code needed to represent that the Symphony Software Foundation was the copyright holder, but this was an unfortunate mistake - in virtually all cases, copyright remains held by the contributor of the project, and (via the CCLA / ICLA) is _licensed_ to the Foundation.

In preparation for a v1.0 release of the Hubot ↔︎ Symphony integration, it would be ideal if the copyright notices in the [NOTICE file](https://github.com/symphonyoss/hubot-symphony/blob/master/NOTICE) and headers of all source code files were updated to show the correct copyright holder of the contribution.

**Comment by jonfreedman** [comment]
That's done in https://github.com/symphonyoss/hubot-symphony/commit/d9a4dcc5c31077db1710a23c6dca3c0a2b50c774

**Comment by pmonks** [comment]
Thanks @jonfreedman - love the speedy turnaround!  And apologies for the instructions previously being wrong.
